name: Semgrep OSS scan
on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep@sha256:0af46ee89d50961490e84024f04ecd78627902588aa97b289a169f9417c38215 # v1.157.0
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1
      - run: semgrep scan --config=auto
